/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TargetViewer;

import java.awt.Color;

import hsa2.GraphicsConsole;

public class App {
    NTInterface networktable = new NTInterface("vision", 5024);
    GraphicsConsole gc = new GraphicsConsole(800, 600, "TargetViewer");

    public static void main(String[] args) {
        new App();
    }

    App() {
        setup();

        while (true) {
            loop();
            gc.sleep(10);
        }
    }
    
    void setup() {
        gc.setBackgroundColor(Color.BLACK);
        gc.clear();
    }

    void loop() {
        
    }
}
